import Activity from "../types/Activity";

const activityMappings = {
  [Activity.DevCode]: [
    "rstudio",
    "sdv",
    "webplatforminstaller",
    "xts",
    "build",
    "cleardescribe",
    "clearfindco",
    "alm-client",
    "ildasm",
    "ssms",
    "mintty",
    "xming",
    "clearprojexp",
    "clearmrgman",
    "kitty",
    "bc2",
    "bcompare",
    "mobaxterm",
    "webmatrix",
    "mexplore",
    "linqpad",
    "android sdk manager",
    "windows phone application deployment",
    "ilspy",
    "tortoiseproc",
    "xsd",
    "eclipse",
    "fiddler",
    "xamarin",
    "netbeans",
    "intellij",
    "sql",
    "sqlitebrowser",
    "devenv",
    "visual studio",
    "code",
    "vs_enterprise",
    "vs2013",
    "microsoftazuretools",
    "webstorm",
    "phpstorm",
    "source insight",
    "zend",
    "console",
    "powershell",
    "shell",
    "cmd",
    "tasktop",
    "android studio",
    "ide",
    "filezilla",
    "flashfxp",
    "charles",
    "delphi32",
    "modelbrowser",
    "ibq",
    "pyscripter",
    "winmergeu",
    "python",
    "bds",
    "studio64",
    "unity",
    "matlab",
  ],
  [Activity.DevDebug]: [
    "vshost",
    "xde",
    "javaw",
    "debug",
    "bugger",
    "windbg",
    "perfview",
    "cdb",
    "msmunittest",
    "bug",
    "snoop",
    "bushound",
    "hyjalmercurydiag",
  ],
  [Activity.DevReview]: [
    "codeflow",
    "gerrit",
    "stash",
    "kallithea",
    "code review",
    "rhodecode",
    "rietveld",
    "crucible",
    "phabricator",
  ],
  [Activity.DevVc]: [
    "diff",
    "repository",
    "cleardiffbl",
    "cleardlg",
    "cleardiffmrg",
    "clearhistory",
    "clearvtree",
    "sourcetree",
    "svn",
    "tortoiseproc",
    "scm",
    "tfs",
    "push",
    "pull",
    "commit",
    "git",
    "bitbucket",
    "visual studio online",
    "thgw",
    "thg",
  ],
  [Activity.Email]: ["mail", "outlook", "thunderbird", "outlook.com"],
  [Activity.Planning]: [
    "backlog",
    "winproj",
    "trello",
    "wunderlist",
    "todoist",
    "personalanalytics",
    "time tracking",
    "track time",
    "rescuetime",
    "clearquest",
    "scrum",
    "kanban",
    "codealike",
    "jira",
    "rally",
    "versionone",
    "calendar",
    "kalender",
    "sprint",
    "user story",
    "plan",
    "microsoft to-do",
    "to-do",
    "todo",
    "task",
    "aufgabe",
    "vorgangsliste",
    "work item",
    "xmind",
    "flowteams",
  ],
  [Activity.ReadWriteDocument]: [
    "aether",
    "insight3",
    "snagiteditor",
    "confluence",
    "picasa",
    "quora",
    "windows photo viewer",
    "visio",
    "flashmedialiveencoder",
    "photofiltre",
    "jmp",
    "treepad",
    "winword",
    "word",
    "leo",
    "translate",
    "übersetzer",
    "wordpress",
    "mspub",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".ppt",
    ".pub",
    "excel",
    "powerpnt",
    "powerpoint",
    "onenote",
    "evernote",
    "audacity",
    "acrord",
    "sharepoint",
    "pdf",
    "foxitreader",
    "adobe reader",
    "adobe acrobat",
    "reader",
    "glcnd",
    "wiki",
    "keep",
    "google docs",
    "yammer",
    "docs",
    "maxqda",
    "office",
    "paint",
    "gimp",
    "photoshop",
    "lightroom",
    "miktex",
    "texmaker",
    "latex",
    "texstudio",
    "latech studio",
    "photo",
    "creative cloud",
    "foto",
    "picpick",
    "greenshot",
    "honeyview",
    "mendeley",
    "zotero",
  ],
  [Activity.InstantMessaging]: [
    "slack",
    "skype",
    "lync",
    "wechat",
    "sip",
    "g2mlauncher",
    "ciscowebexstart",
    "nbrplay",
    "g2mui",
    "chatter",
    "atmgr",
    "hangout",
    "meet",
    "viber",
    "messaging",
    "whatsapp",
    "messenger",
    "ctimon",
    "signal",
    "ciscojabber",
    "teams",
    "zoom",
    "basecamp",
  ],
  [Activity.FileNavigationInExplorer]: [
    "finder",
    "explorer",
    "speedcommander",
    "q-dir",
    "7zfm",
    "dropbox",
    "everything",
    "winzip32",
    "winzip64",
    "winrar",
  ],
  [Activity.Other]: [
    "mmc",
    "dfsvc",
    "procmon64",
    "mousewithoutboarders",
    "vpnui",
    "dinotify",
    "calculator",
    "time",
    "perfmon",
    "1password",
    "lastpass",
    "keepass",
    "agentransack",
    "lockapp",
    "searchui",
    "pwsafe",
    "wuauclt",
    "calc",
    "wwahost",
    "update",
    "avpui",
    "procexp64",
    "taskmgr",
    "pgp",
    "explorer",
    "groove",
    "spotify",
    "vlc media player",
    "windows camera",
    "dwm",
    "rstrui",
    "snippingtool",
    "screenclippinghost",
    "onedrive",
    "settings",
    "einstellungen",
    "ccleaner64",
    "avira.systray",
    "defender",
    "check point endpoint security",
    "company portal",
    "avscan",
    "rzsynapse",
    "winstore.app",
    "gazenative8",
    "devicepairingwizard",
    "printui",
    "sapisvr",
    "msaccess",
    "audacity",
    "icofx3",
    "news",
    "twitchui",
  ],
  [Activity.OtherRdp]: [
    "rdcman",
    "mstsc",
    "vmconnect",
    "virtualbox",
    "vmware",
    "vpxclient",
    "msiexec",
    "pageant",
    "putty",
    "mremote",
    "mremoteng",
  ],
  [Activity.Gaming]: ["farcry4", "battle.net"],
} as const;

export default activityMappings;
