import Activity from "../types/Activity";

const activityMappings = {
  [Activity.DevCode]: [
    "rstudio",
    "sdv",
    "nodejs",
    "s3",
    "twilio",
    "ecs",
    "docker",
    "tableau",
    "circleci",
    "sendgrid",
    "webplatforminstaller",
    "xts",
    "build",
    "cleardescribe",
    "clearfindco",
    "jupyter",
    "collab",
    "mariadb",
    "mongodb",
    "stripe",
    "vercel",
    "azure",
    "aws",
    "google cloud",
    "electron",
    "angular",
    "react",
    "travis",
    "newrelic",
    "db2",
    "redis",
    "elasticsearch",
    "cassandra",
    "orientdb",
    "neo4j",
    "dynamodb",
    "reviewboard",
    "codespace",
    "alm-client",
    "ildasm",
    "ssms",
    "mintty",
    "xming",
    "clearprojexp",
    "clearmrgman",
    "kitty",
    "bc2",
    "bcompare",
    "mobaxterm",
    "webmatrix",
    "mexplore",
    "linqpad",
    "android sdk manager",
    "windows phone application deployment",
    "ilspy",
    "tortoiseproc",
    "xsd",
    "eclipse",
    "fiddler",
    "xamarin",
    "netbeans",
    "intellij",
    "sql",
    "sqlitebrowser",
    "devenv",
    "visual studio",
    "code",
    "mono", // includes mono develop
    "vs_enterprise",
    "vs2013",
    "webstorm",
    "phpstorm",
    "source insight",
    "zend",
    "console",
    "bash", // includes git bash
    "powershell",
    "shell",
    "cmd",
    "komodo",
    "aptana",
    "visual expert",
    "jcreator",
    "drjava",
    "zend studio",
    "coda 2",
    "eric python",
    "tasktop",
    "android studio",
    "pycharm",
    "ide",
    "filezilla",
    "flashfxp",
    "charles",
    "delphi32",
    "modelbrowser",
    "ibq",
    "qt", // includes Qt creato
    "pyscripter",
    "winmergeu",
    "python",
    "bds",
    "studio64",
    "unity",
    "matlab",
    "xcode"
  ],
  [Activity.DevDebug]: [
    "vshost",
    "xde",
    "javaw",
    "debug",
    "bugger",
    "windbg",
    "perfview",
    "cdb",
    "msmunittest",
    "bug",
    "snoop",
    "bushound",
    "hyjalmercurydiag",
    "localhost"
  ],
  [Activity.DevReview]: [
    "codeflow",
    "gerrit",
    "stash",
    "kallithea",
    "code review",
    "rhodecode",
    "rietveld",
    "crucible",
    "phabricator",
  ],
  [Activity.DevVc]: [
    "git", // includes github, gitlab
    "diff",
    "repository",
    "cleardiffbl",
    "cleardlg",
    "cleardiffmrg",
    "clearhistory",
    "clearvtree",
    "sourcetree",
    "svn",
    "tortoiseproc",
    "scm",
    "tfs",
    "push",
    "pull",
    "commit",
    "bitbucket",
    "visual studio online",
    "thgw",
    "thg",
  ],
  [Activity.Email]: [
    "mail", // includes gmail, proton mail, apple mail, canary mail, mailsprint, mailbird, edison mail
    "outlook", // includes outlook.com
    "thunderbird", 
    "gmail",
    "hey",
    "superhuman",
    "spark",
    "postbox",
    "kiwi"
  ],
  [Activity.Planning]: [
    "backlog",
    "atlassian",
    "ical",
    "calendly",
    "hakuna",
    "clocker",
    "linear",
    "getplan",
    "airtable",
    "omnifocus",
    "tickctick",
    "mattermost",
    "airtable",
    "productboard",
    "winproj",
    "trello",
    "wunderlist",
    "todoist",
    "personalanalytics",
    "time tracking",
    "track time",
    "rescuetime",
    "clearquest",
    "scrum",
    "kanban",
    "codealike",
    "jira",
    "rally",
    "versionone",
    "calendar",
    "kalender",
    "sprint",
    "user story",
    "plan", // includes Microsoft Planner
    "project", // includes Microsoft Project
    "microsoft to-do",
    "to-do",
    "todo",
    "task",
    "aufgabe",
    "vorgangsliste",
    "work item",
    "xmind",
    "monday.com",
    "clickup",
    "flowteams",
  ],
  [Activity.ReadWriteDocument]: [
    "aether",
    "insight3",
    "snagiteditor",
    "confluence",
    "form", // includes typeform, microsoft forms, google forms
    "survey", // includes surveymonkey, surveyplanet
    "jotform", 
    "qualtrics",
    "mailchimp",
    "grammarly",
    "hubspot",
    "autocad",
    "quora",
    "visio",
    "flashmedialiveencoder",
    "jmp",
    "treepad",
    "winword",
    "word",
    "leo",
    "dictionary",
    "translate",
    "deepl",
    "translator",
    "dict.cc",
    "übersetzer",
    "wordpress",
    "mspub",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".ppt",
    ".pub",
    "excel",
    "powerpnt",
    "powerpoint",
    "pages",
    "keynote",
    "onenote",
    "evernote",
    "audacity",
    "acrord",
    "sharepoint",
    "pdf",
    "foxitreader",
    "adobe reader",
    "adobe acrobat",
    "reader",
    "glcnd",
    "wiki",
    "keep",
    "google docs",
    "yammer",
    "docs",
    "maxqda",
    "office",
    "miktex",
    "texmaker",
    "latex",
    "goodnotes",
    "ulysses",
    "textedit",
    "obsidian",
    "overleaf",
    "texstudio",
    "latech studio",
    "photo",
    "foto",
    "picpick",
    "greenshot",
    "honeyview",
    "mendeley",
    "zotero",
  ],
  [Activity.Design]: [
    "invisionapp.com",
    "unsplash.com",
    "readymag.com",
    "jam.dev",
    "canva.com",
    "sketch",
    "creative cloud",
    "figma",
    "zeplin",
    "adobe illustrator",
    "photoshop",
    "adobe xd",
    "indesign",
    "picasa",
    "illustrator",
    "sketchUp",
    "paint",
    "windows photo viewer",
    "photofiltre",
    "gimp",   
  ],
  [Activity.SocialMedia]: [
    "instagram",
    "flickr",
    "facebook",
    "reddit",
    "twitter", // we cannot match X since there will be many false-positives
    "tumblr",
    "threads",
    "youtube",
    "tiktok",
    "snapchat",
    "pinterest",
  ],
  [Activity.GenerativeAI]: [
    "openai", 
    "chatgpt", 
    "gpt", 
    "copilot", 
    "gemini", 
    "bard", 
    "claude", 
    "cohere", 
    "synthesia", 
    "dall-e", 
    "midjourney", 
    "generative", 
    "codewhisperer", 
    "tabnine", 
    "codewp", 
    "codesquire"
  ],
  [Activity.InstantMessaging]: [
    "chat", // includes wechat, chatter
    "slack",
    "skype",
    "lync",
    "discord",
    "sip", // includes MicroSIP
    "mqtt",
    "g2mlauncher",
    "nbrplay",
    "g2mui",
    "atmgr",
    "hangout",
    "meet", // includes Google Meet
    "viber",
    "messaging",
    "whatsapp",
    "messenger",
    "ctimon",
    "bluejeans",
    "signal",
    "threema",
    "telegram",
    "tandem",
    "facetime",
    "gotomeeting",
    "ciscowebexstart",
    "anydesk",
    "ciscospark",
    "ciscojabber",
    "teams",
    "zoom",
    "basecamp",
    "voip" // includes PhonerLite VoIP Softphone
  ],
  [Activity.FileManagement]: [
    "finder",
    "explorer",
    "speedcommander",
    "q-dir",
    "7zfm",
    "everything",
    "winzip32",
    "winzip64",
    "winrar",
    "onedrive",
    "googledrive",
    "google drive",
    "box", // includes box, dropbox
    "mega", 
    "icloud",
  ],
  [Activity.Other]: [
    "mmc",
    "dfsvc",
    "procmon64",
    "mousewithoutboarders",
    "vpnui",
    "dinotify",
    "calculator",
    "time",
    "perfmon",
    "1password",
    "lastpass",
    "keepass",
    "agentransack",
    "lockapp",
    "searchui",
    "pwsafe",
    "wuauclt",
    "calc", // includes calculator
    "rechner",
    "wwahost",
    "update",
    "avpui",
    "procexp64",
    "taskmgr",
    "activity monitor",
    "clean my mac",
    "pgp",
    "groove",
    "spotify",
    "vlc media player",
    "windows camera",
    "dwm",
    "rstrui",
    "snippingtool",
    "screenclippinghost",
    "settings",
    "einstellungen",
    "ccleaner64",
    "avira.systray",
    "defender",
    "check point endpoint security",
    "company portal",
    "avscan",
    "rzsynapse",
    "winstore.app",
    "gazenative8",
    "devicepairingwizard",
    "printui",
    "sapisvr",
    "msaccess",
    "audacity",
    "icofx3",
    "news",
    "twitchui",
  ],
  [Activity.OtherRdp]: [
    "rdcman",
    "mstsc",
    "vmconnect",
    "virtualbox",
    "vmware",
    "remotedesktop",
    "vpxclient",
    "msiexec",
    "pageant",
    "putty",
    "mremote",
    "mremoteng",
  ],
} as const;

export default activityMappings;
