const devCode = [
  "rstudio",
  "sdv",
  "nodejs",
  "s3",
  "twilio",
  "ecs",
  "docker",
  "tableau",
  "circleci",
  "sendgrid",
  "webplatforminstaller",
  "xts",
  "build",
  "cleardescribe",
  "clearfindco",
  "jupyter",
  "collab",
  "mariadb",
  "mongodb",
  "stripe",
  "vercel",
  "azure",
  "aws",
  "google cloud",
  "electron",
  "angular",
  "react",
  "travis",
  "newrelic",
  "db2",
  "redis",
  "elasticsearch",
  "cassandra",
  "orientdb",
  "neo4j",
  "dynamodb",
  "reviewboard",
  "codespace",
  "alm-client",
  "ildasm",
  "ssms",
  "mintty",
  "xming",
  "clearprojexp",
  "clearmrgman",
  "kitty",
  "bc2",
  "bcompare",
  "mobaxterm",
  "webmatrix",
  "mexplore",
  "linqpad",
  "android sdk manager",
  "windows phone application deployment",
  "ilspy",
  "tortoiseproc",
  "xsd",
  "eclipse",
  "fiddler",
  "xamarin",
  "netbeans",
  "intellij",
  "sql",
  "sqlitebrowser",
  "devenv",
  "visual studio",
  "code",
  "mono", // includes mono develop
  "vs_enterprise",
  "vs2013",
  "webstorm",
  "phpstorm",
  "source insight",
  "zend",
  "console",
  "bash", // includes git bash
  "powershell",
  "shell",
  "cmd",
  "komodo",
  "aptana",
  "visual expert",
  "jcreator",
  "drjava",
  "zend studio",
  "coda 2",
  "eric python",
  "tasktop",
  "android studio",
  "pycharm",
  "ide",
  "filezilla",
  "flashfxp",
  "charles",
  "delphi32",
  "modelbrowser",
  "ibq",
  "qt", // includes Qt creator
  "pyscripter",
  "winmergeu",
  "python",
  "bds",
  "studio64",
  "unity",
  "matlab",
  "xcode"
];

export default devCode;
