export const process = [
  "rstudio",
  "sdv",
  "node",
  "docker",
  "tableau",
  "webplatforminstaller",
  "build",
  "cleardescribe",
  "clearfindco",
  "jupyter",
  "mariadb",
  "godot",
  "mongodb",
  "electron",
  "db2",
  "redis",
  "elasticsearch",
  "cassandra",
  "orientdb",
  "neo4j",
  "alm-client",
  "ildasm",
  "ssms",
  "mintty",
  "xming",
  "clearprojexp",
  "clearmrgman",
  "kitty",
  "bc2",
  "bcompare",
  "mobaxterm",
  "webmatrix",
  "mexplore",
  "linqpad",
  "ilspy",
  "xsd",
  "eclipse",
  "fiddler",
  "xamarin",
  "netbeans",
  "intellij",
  "sql",
  "sqlitebrowser",
  "devenv",
  "visual studio",
  "visual studio code",
  "code",
  "mono", // includes mono develop
  "webstorm",
  "phpstorm",
  "source insight",
  "zend",
  "console",
  "bash", // includes git bash
  "powershell",
  "shell",
  "terminal",
  "cmd",
  "komodo",
  "aptana",
  "visual expert",
  "jcreator",
  "drjava",
  "zend studio",
  "coda",
  "tasktop",
  "android studio",
  "pycharm",
  "ide",
  "filezilla",
  "flashfxp",
  "charles",
  "delphi32",
  "modelbrowser",
  "ibq",
  "qt", // includes Qt creator
  "pyscripter",
  "winmergeu",
  "python",
  "bds",
  "studio64",
  "unity",
  "matlab",
  "xcode",
  "thonny", // Python IDE for beginners
  "pgadmin", // PostgreSQL admin tool
];

// title keywords: only matched in browser context
export const title = [
  "android sdk manager",        
  "powerapps",
  "angular",
  "react",
  "typescript",
  "php",
  ".net",
  "c#",
  "java",
  "jupyterlab",
  "s3",
  "twilio",
  "ecs",
  "circleci",
  "sendgrid",
  "amazon web service",
  "geek",
  "telerik",
  "vbforums",
  "stripe",
  "vercel",
  "dynamodb",
  "codespace",
  "reviewboard",
  "travis",
  "newrelic",
  "collab",
  "stack overflow",
  "msdn",
  "azure",
  "aws",
  "google cloud",
  "alibaba cloud"
];
