const generativeAI = [
  "openai",
  "chatgpt",
  "gpt",
  "copilot", // Github and Microsoft
  "gemini",
  "claude",
  "cohere",
  "synthesia",
  "dall-e",
  "midjourney",
  "generative",
  "codewhisperer",
  "tabnine",
  "codewp",
  "codesquire",
  "deepseek",
  "grok",
  "perplexity",
  "ollama",
  "mistral",
  "codeium",
  "windsurf",
  "elevenlabs",
  "notebooklm",
  "huggingface",
  "stable diffusion",
  "cursor",
  "runway",
  "leonardo",
  "firefly",
  "qwen",
];

export default generativeAI;
