export const process = [
  "mmc",
  "dfsvc",
  "procmon64",
  "mousewithoutboarders",
  "vpnui",
  "dinotify",
  "calculator",
  "perfmon",
  "1password",
  "lastpass",
  "keepass",
  "agentransack",
  "lockapp",
  "pwsafe",
  "wuauclt",
  "calc", // includes calculator
  "rechner",
  "wwahost",
  "avpui",
  "procexp64",
  "taskmgr",
  "task manager", // display name variant of taskmgr
  "activity monitor",
  "pgp",
  "groove",
  "spotify",
  "vlc",
  "windows camera",
  "dwm",
  "rstrui",
  "snippingtool",
  "screenclippinghost",
  "ccleaner64",
  "avira.systray",
  "defender",
  "company portal",
  "avscan",
  "rzsynapse",
  "winstore.app",
  "gazenative8",
  "devicepairingwizard",
  "printui",
  "sapisvr",
  "msaccess",
  "audacity",
  "icofx3",
];

// title keywords: only matched in browser context
export const title = [
  "settings",
  "einstellungen",
];
