const other = [
  "mmc",
  "dfsvc",
  "procmon64",
  "mousewithoutboarders",
  "vpnui",
  "dinotify",
  "calculator",
  "time",
  "perfmon",
  "1password",
  "lastpass",
  "keepass",
  "agentransack",
  "lockapp",
  "searchui",
  "pwsafe",
  "wuauclt",
  "calc", // includes calculator
  "rechner",
  "wwahost",
  "update",
  "avpui",
  "procexp64",
  "taskmgr",
  "activity monitor",
  "clean my mac",
  "pgp",
  "groove",
  "spotify",
  "vlc media player",
  "windows camera",
  "dwm",
  "rstrui",
  "snippingtool",
  "screenclippinghost",
  "settings",
  "einstellungen",
  "ccleaner64",
  "avira.systray",
  "defender",
  "check point endpoint security",
  "company portal",
  "avscan",
  "rzsynapse",
  "winstore.app",
  "gazenative8",
  "devicepairingwizard",
  "printui",
  "sapisvr",
  "msaccess",
  "audacity",
  "icofx3",
  "news",
  "twitchui",
];

export default other;
