const planning = [
  "backlog",
  "atlassian",
  "ical",
  "calendly",
  "hakuna",
  "clocker",
  "linear",
  "getplan",
  "airtable",
  "omnifocus",
  "tickctick",
  "mattermost",
  "productboard",
  "winproj",
  "trello",
  "wunderlist",
  "todoist",
  "personalanalytics",
  "time tracking",
  "track time",
  "rescuetime",
  "clearquest",
  "scrum",
  "kanban",
  "codealike",
  "jira",
  "rally",
  "versionone",
  "calendar",
  "kalender",
  "sprint",
  "user story",
  "plan", // includes Microsoft Planner
  "project", // includes Microsoft Project
  "microsoft to-do",
  "to-do",
  "todo",
  "task",
  "aufgabe",
  "vorgangsliste",
  "work item",
  "xmind",
  "monday.com",
  "clickup",
  "flowteams",
];

export default planning;
