const readWriteDocument = [
  "aether",
  "insight3",
  "snagiteditor",
  "confluence",
  "form", // includes typeform, microsoft forms, google forms
  "survey", // includes surveymonkey, surveyplanet
  "jotform",
  "qualtrics",
  "mailchimp",
  "grammarly",
  "hubspot",
  "autocad",
  "quora",
  "visio",
  "flashmedialiveencoder",
  "jmp",
  "treepad",
  "winword",
  "word",
  "leo",
  "dictionary",
  "translate",
  "deepl",
  "translator",
  "dict.cc",
  "übersetzer",
  "wordpress",
  "mspub",
  ".doc",
  ".docx",
  ".xls",
  ".xlsx",
  ".ppt",
  ".pub",
  "excel",
  "powerpnt",
  "powerpoint",
  "pages",
  "keynote",
  "onenote",
  "evernote",
  "audacity",
  "acrord",
  "sharepoint",
  "pdf",
  "foxitreader",
  "adobe reader",
  "adobe acrobat",
  "reader",
  "glcnd",
  "wiki",
  "keep",
  "google docs",
  "yammer",
  "docs",
  "maxqda",
  "office",
  "miktex",
  "texmaker",
  "latex",
  "goodnotes",
  "ulysses",
  "textedit",
  "obsidian",
  "overleaf",
  "texstudio",
  "latech studio",
  "photo",
  "foto",
  "picpick",
  "greenshot",
  "honeyview",
  "mendeley",
  "zotero",
];

export default readWriteDocument;
