export const process = [
  "aether",
  "insight3",
  "snagiteditor",
  "confluence",
  "grammarly",
  "autocad",
  "visio",
  "jmp",
  "treepad",
  "winword",
  "word",
  "mspub",
  "excel",
  "powerpnt",
  "powerpoint",
  "keynote",
  "onenote",
  "evernote",
  "notion",
  "notes", // Apple notes
  "microsoft.notes",
  "endnote",
  "numbers", // Apple spreadsheet app
  "remnote",
  "acrord",
  "foxitreader",
  "adobe reader",
  "adobe acrobat",
  "reader",
  "glcnd",
  "maxqda",
  "office",
  "miktex",
  "texmaker",
  "latex",
  "goodnotes",
  "ulysses",
  "textedit",
  "obsidian",
  "texstudio",
  "latech studio",
  "picpick",
  "greenshot",
  "honeyview",
  "mendeley",
  "zotero",
  "apple pages",
  "msaccess",
  "imagej",
  "cmi.client.main",
  "biolucidaviewer",
  "mim",
  "olat",
  "spss",
  "qgis", // GIS software
  "notability", // note-taking app
  "anki", // flashcard/spaced repetition
  "preview", // macOS Preview
  "journal", // Windows/Apple Journal
  "express scribe", // transcription software
  "okular", // KDE document viewer
  "nebo", // handwriting note-taking
  "stickies", // sticky notes app
];

// title keywords: only matched in browser context
export const title = [
  "typeform",
  "microsoft forms",
  "google forms", 
  "survey", // includes surveymonkey, surveyplanet
  "umfrage",
  "jotform",
  "qualtrics",
  "mailchimp",
  "overleaf",
  "quora",
  "dictionary",
  "translate",
  "translator",
  "dict.cc",
  "leo",
  "deepl",
  "github pages",
  "wordpress",
  "übersetzer",
  "wiki",
  "hubspot",
  "keep",
  "google docs",
  "docs",
  ".doc",
  ".docx",
  ".xls",
  ".xlsx",
  ".ppt",
  ".pub",
  "pdf",
  "photo",
  "foto",
  "arxiv",
  "scholar",
  "lecture",
  "vorlesung",
];
