const workRelatedWebsites = [
  "linkedin",
  "substack",
  "yammer",
  "viva insights",
  "viva learning",
  "viva amplify",
  "viva engage",
  "viva connections",
  "viva glint",
  "viva pulse",
  "calculator",
  "analytics",
  "azure",
  "power bi",
  "business",
  "googleearth",
  "centmin",
  "ios",
  "cyon",
  "rize",
  "salesforce.com",
  "mylyn",
  "jetbrains",
  "salesforce",
  "sap",
  "kindle",
  "medium",
  "testcomplete",
  "application lifecycle management",
  "all reports",
  "dashboard",
  "virtualbox",
  "document",
  "proxy",
  "jenkins",
  "databasics",
  "abb",
  "shadowbot",
  "office",
  "namespace",
  "api",
  "apache",
  "oracle",
  "server",
  "system",
  "ibm",
  "code",
  "retrospection",
  "developer",
  "documentation",
  "blog",
  "coding",
  "programmer",
];

export default workRelatedWebsites;
