const workRelatedWebsites = [
  "linkedin",
  "techready",
  "powerapps",
  "angular",
  "connect",
  "typescript",
  "release",
  "batmon",
  "calculator",
  "analytics",
  "azure",
  "power bi",
  "business",
  "googleearth",
  "php",
  "proffix",
  "centmin",
  "picturex",
  "ios",
  "schmelzmetall",
  "natur- und tierpark goldau",
  "tierpark",
  "amazon web service",
  "cyon",
  "salesforce.com",
  "silverlight",
  "issue",
  "junit",
  "mylyn",
  "jetbrains",
  "telerik",
  "testcomplete",
  "application lifecycle management",
  "all reports",
  "advanced search",
  ".net",
  "c#",
  "java",
  "vbforums",
  "dashboard",
  "virtualbox",
  "document",
  "dropbox",
  "onedrive",
  "proxy",
  "jenkins",
  "databasics",
  "suite",
  "abb",
  "shadowbot",
  "office",
  "windows",
  "namespace",
  "ventyx",
  "api",
  "apache",
  "oracle",
  "server",
  "system",
  "ibm",
  "code",
  "codeplex",
  "retrospection",
  "stack overflow",
  "msdn",
  "developer",
  "documentation",
  "blog",
  "coding",
  "programmer",
];

export default workRelatedWebsites;
